POST http://localhost:3333/register/client
Content-Type: application/json
Accept: application/json

{
    "name": "Dona Creuza",
    "email": "DonaCreuza@gmail.com",
    "password": "DonaCreuza123"
}

###

POST http://localhost:3333/login/client
Content-Type: application/json
Accept: application/json

{
    "name": "Dona Creuza",
    "email": "DonaCreuza@gmail.com",
    "password": "DonaCreuza123"
}
###
POST http://localhost:3333/update/client
Content-Type: application/json
Accept: application/json

{
    "id": "eaefd3f6-d072-408d-8c2b-4bdde84dc7bc",
    "oldName": "Nova Dona Creuza",
    "newName": "Dona",
    "oldEmail": "DonaCreuzaNova@gmail.com",
    "newEmail": "Quero@gmail.com",
    "oldPassword": "QueroMaisDonaCreuzaNão",
    "newPassword": "12345678"
}

###
GET http://localhost:3333/get/client/eaefd3f6-d072-408d-8c2b-4bdde84dc7bc

###

GET http://localhost:3333/get/client/list

###

DELETE http://localhost:3333/delete/client/list